# Generated by Django 5.2.1 on 2025-05-26 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('quantidade_pessoas', models.IntegerField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='reservada', max_length=10)),
                ('garcom_confirmador', models.CharField(blank=True, max_length=100, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.mesa')),
            ],
        ),
    ]
